# Generated by Django 4.1 on 2022-09-04 03:59

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('body', markdownx.models.MarkdownxField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('lifespan', models.DurationField()),
                ('maturity', models.IntegerField(choices=[(1, 'Seedline'), (2, 'Sapling'), (3, 'Mature'), (4, 'Decline')], default=1)),
                ('importance', models.IntegerField(choices=[(1, 'Not At All Important'), (2, 'Low Importance'), (3, 'Neutral'), (4, 'Very Important'), (5, 'Extremely Important')])),
                ('likelihood', models.IntegerField(choices=[(1, 'Impossible'), (2, 'Remote'), (3, 'Highly Unlikely'), (4, 'Unlikely'), (5, 'Possible'), (6, 'Likely'), (7, 'Highly Likely'), (8, 'Certain')])),
            ],
        ),
        migrations.CreateModel(
            name='NoteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.note')),
            ],
        ),
    ]
